name: wf
on: [push]
jobs:
    fist_job:
        runs-on: ubuntu-latest
        steps: 
        - name: checkoout
          uses: actions/checkout@v5

        - name: welcome
          run: echo "welcome"
        - name: list
          run: ls
        - name: read
          run: cat README.md